run1 :
	rm -f *.png
	python KRR_12.py "./Input_1.txt" "./a_x_1.txt"

run2 :
	rm -f *.png
	python KRR_12.py "./Input_2.txt" "./a_x_2.txt"

run3 :
	rm -f *.png
	python KRR_12.py "./Input_3.txt" "./a_x_3.txt"

run4 :
	rm -f *.png
	python KRR_12.py "./Input_4.txt" "./a_x_4.txt"