from pylab import *
# #practice worksamples
# x=linspace(0,2*pi,128)
# y=sin(5*x)
# Y=fft(y)
# figure()
# subplot(2,1,1)
# plot(abs(Y),lw=2)
# ylabel(r"$|Y|$",size=16)
# title(r"Spectrum of $\sin(5t)$")
# grid(True)
# subplot(2,1,2)
# plot(unwrap(angle(Y)),lw=2)
# ylabel(r"Phase of $Y$",size=16)
# xlabel(r"$k$",size=16)
# grid(True)
# show()
# # #

# x=linspace(0,2*pi,129)
# x=x[:-1]
# y=sin(5*x)
# Y=fftshift(fft(y))/128.0
# w=linspace(-64,63,128)
# figure()
# subplot(2,1,1)
# plot(w,abs(Y),lw=2)
# xlim([-10,10])
# ylabel(r"$|Y|$",size=16)
# title(r"Spectrum of $\sin(5t)$")
# grid(True)
# subplot(2,1,2)
# plot(w,abs(Y),'ro',lw=2)
# ii=where(abs(Y)>1e-3)
# plot(w[ii],angle(Y[ii]),'go',lw=2)
# xlim([-10,10])
# ylabel(r"Phase of $Y$",size=16)
# xlabel(r"$k$",size=16)
# grid(True)
# show()

# # #
# t=linspace(0,2*pi,129);t=t[:-1]
# y=(1+0.1*cos(t))*cos(10*t)
# Y=fftshift(fft(y))/128.0
# w=linspace(-64,63,128)
# figure()
# subplot(2,1,1)
# plot(w,abs(Y),lw=2)
# xlim([-15,15])
# ylabel(r"$|Y|$",size=16)
# title(r"Spectrum of $\left(1+0.1\cos\left(t\right)\right)\cos\left(10t\right)$")
# grid(True)
# subplot(2,1,2)
# plot(w,angle(Y),'ro',lw=2)
# xlim([-15,15])
# ylabel(r"Phase of $Y$",size=16)
# xlabel(r"$\omega$",size=16)
# grid(True)
# show()
# # #
# t=linspace(-4*pi,4*pi,513);t=t[:-1]
# y=(1+0.1*cos(t))*cos(10*t)
# Y=fftshift(fft(y))/512.0
# w=linspace(-64,64,513);w=w[:-1]
# figure()
# subplot(2,1,1)
# plot(w,abs(Y),lw=2)
# xlim([-15,15])
# ylabel(r"$|Y|$",size=16)
# title(r"Spectrum of $\left(1+0.1\cos\left(t\right)\right)\cos\left(10t\right)$")
# grid(True)
# subplot(2,1,2)
# plot(w,angle(Y),'ro',lw=2)
# xlim([-15,15])
# ylabel(r"Phase of $Y$",size=16)
# xlabel(r"$\omega$",size=16)
# grid(True)
# show()
#assignment
#sin^3t spectrum
x=linspace(-4*pi,4*pi,513)
x=x[:-1]
y=pow(sin(x),3)
Y=fftshift(fft(y))/512.0
w=linspace(-64,64,513)
w=w[:-1]
figure()
subplot(2,1,1)
plot(w,abs(Y),lw=2)
xlim([-10,10])
ylabel(r"$|Y|$",size=16)
title(r"Spectrum of $\sin^3(t)$")
grid(True)
subplot(2,1,2)
plot(w,abs(Y),'ro',lw=2)
ii=where(abs(Y)>1e-3)
plot(w[ii],angle(Y[ii]),'go',lw=2)
xlim([-10,10])
ylabel(r"Phase of $Y$",size=16)
xlabel(r"$k$",size=16)
grid(True)
show()
# #cos^3t spectrum
# x=linspace(-4*pi,4*pi,513)
# x=x[:-1]
# y=pow(cos(x),3)
# Y=fftshift(fft(y))/512.0
# w=linspace(-64,64,513)
# w=w[:-1]
# figure()
# subplot(2,1,1)
# plot(w,abs(Y),lw=2)
# xlim([-10,10])
# ylabel(r"$|Y|$",size=16)
# title(r"Spectrum of $\cos^3(t)$")
# grid(True)
# subplot(2,1,2)
# plot(w,abs(Y),'ro',lw=2)
# ii=where(abs(Y)>1e-3)
# plot(w[ii],angle(Y[ii]),'go',lw=2)
# xlim([-10,10])
# ylabel(r"Phase of $Y$",size=16)
# xlabel(r"$k$",size=16)
# grid(True)
# show()
# #
# x=linspace(-4*pi,4*pi,513)
# x=x[:-1]
# y=cos(20*x+5*cos(x)) 
# Y=fftshift(fft(y))/512.0
# w=linspace(-64,64,513)
# w=w[:-1]
# figure()
# subplot(2,1,1)
# plot(w,abs(Y),lw=2)
# xlim([-30,30])
# ylabel(r"$|Y|$",size=16)
# title(r"Spectrum of $\cos(20t+5cos(t))$")
# grid(True)
# subplot(2,1,2)
# plot(w,angle(Y),'ro',lw=2)
# ii=where(abs(Y)>1e-3)
# plot(w[ii],angle(Y[ii]),'go',lw=2)
# xlim([-30,30])
# ylabel(r"Phase of $Y$",size=16)
# xlabel(r"$k$",size=16)
# grid(True)
# show()
# #
# x=linspace(-4*pi,4*pi,513)
# x=x[:-1]
# y=exp(-(x*x)/2.0)
# Y=fftshift(fft(fftshift(y)))*8*pi/512.0
# w=linspace(-64,64,513)
# w=w[:-1]
# figure()
# subplot(2,1,1)
# plot(w,abs(Y),lw=2)
# xlim([-30,30])
# ylabel(r"$|Y|$",size=16)
# title(r"Spectrum of $\exp(-t^2/2)$")
# grid(True)
# subplot(2,1,2)
# plot(w,angle(Y),'ro',lw=2)
# ii=where(abs(Y)>1e-6)
# plot(w[ii],angle(Y[ii]),'go',lw=2)
# xlim([-30,30])
# ylabel(r"Phase of $Y$",size=16)
# xlabel(r"$k$",size=16)
# grid(True)
# show()